Repository amandewatnitrr/hacking-tutorial, pull requests merged in 2025-10, with the labels that each got.

#7 lesson on phishing toolkit added
  ethical-hacking/lesson-07.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#12 feat: Add script for WPA/WPA2 dictionary attack automation
  python-scripts/wpa2_dictionary_attack.py
Labels: enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted

#18 Adding Cybersecurity Resources
  README.md
Labels: documentation, good first issue, wontfix, hacktoberfest, hacktoberfest-accepted

#14 created a lesson on fing and its uses in ethical hacking
  ethical-hacking/lesson-fing.md
  imgs/l1.png
  imgs/l2.png
  imgs/l3.png
  imgs/l4.png
Labels: enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted

#20 feat: add async port scanner with banner grabbing, demo & tests
  python-scripts/async_port_scanner.py
  python-scripts/portscanner_test.py
  python-scripts/remote_collect_via_ssh.py
Labels: enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted

#17 added lesson on rsa encryption
  ethical-hacking/lesson-rsa.md
  imgs/ll2.png
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#26 added a questionnaire
  .DS_Store
  safe-practice-questions/answer-key.md
  safe-practice-questions/questions.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#24 feat: Add HTTPS fetcher using bettercap
  python-scripts/https_data_fetcher_bettercap.py
Labels: enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted

#30 new lesson added
  ethical-hacking/lesson-password_attack-and_hashcracking.md
Labels: documentation, enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted

#33 new python script
  python-scripts/wordlist_generator.py
Labels: enhancement, help wanted, good first issue, priority, hacktoberfest, hacktoberfest-accepted
